### PR TITLE
Trap modal focus by disabling all focusable elements outside of its content.

### PR DESCRIPTION
**Pull request by isoos**
#7308

### CODE REVIEW

**Comment by isoos** [comment]
Note: deploying to staging.

**Comment by sigurdm** [comment]
Should also be enabled for the screenshot carousel.

If I try this on the admin page the drop-down selector "select a publisher" still gets focus

This approach seems very fragile (what if we forget a selector?) but I guess there is no native html functionality to support this directly...

**Comment by sigurdm** [comment]
I think `:focus-within` can be used for determining which elements are inside the modal...
https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within
https://caniuse.com/?search=focus-within

**Comment by isoos** [comment]
> This approach seems very fragile (what if we forget a selector?)

Worst case: we have a rogue focus somewhere. Commented on the issue the two main approaches that we could take, and I think this is the more graceful failure we could have. The other approach (catching and redirecting the focus) seems to be more brittle.

> If I try this on the admin page the drop-down selector "select a publisher" still gets focus

Good catch, my local test didn't have a publisher. Fixed the `tabindex` handling, as material select had some unexpected use of it.

> Should also be enabled for the screenshot carousel.

I wanted to address that separately, and also wanted to verify if this doesn't introduce something that is broken/fragile with integration test on CI.

**Comment by isoos** [comment]
`:focus-within` is great for styling (we are using it at other places), but I don't see how it could be used for focus trapping, other than the listening on all focus events and rewriting the default focus behavior.

**Comment by sigurdm** [comment]
> `:focus-within` is great for styling (we are using it at other places), but I don't see how it could be used for focus trapping, other than the listening on all focus events and rewriting the default focus behavior.

Yeah, I meant it only for the `_isInsideContent` calculation, not as a way to disable focus in general. :/

**Comment by sigurdm** [comment]
> Worst case: we have a rogue focus somewhere. 

Yeah that's probably not too bad.

> Commented on the issue the two main approaches that we could take, and I think this is the more graceful failure we could have. The other approach (catching and redirecting the focus) seems to be more brittle.

I agree!

**Review by sigurdm — APPROVED** [review]

**Pull request merged**
