### PR TITLE
Provide width and height for sparkline

### PR DESCRIPTION
**Pull request by sigurdm**
Fixes https://github.com/dart-lang/pub-dev/issues/8400

Tested manually with Safari:

image

### CODE REVIEW

**Review by isoos — APPROVED** [review]

**Comment by isoos** [comment]
Nit: wouldn't it be better to set these in CSS?

**Comment by sigurdm** [comment]
> Nit: wouldn't it be better to set these in CSS?

YES! That is much smarter.

Which style-file would you put this into?

**Comment by isoos** [comment]
Somewhere here maybe: https://github.com/dart-lang/pub-dev/blob/master/pkg/web_css/lib/src/_detail_page.scss#L238-L285

**Comment by sigurdm** [comment]
It doesn't work - safari needs these to be set as attributes, not as part of the style it seems.

**Pull request merged**
