### PR TITLE
Update layout.mustache

### PR DESCRIPTION
**Pull request by mit-mit**
- Add a few more relevant doc links
- Make caps consistent

### CODE REVIEW

**Comment by isoos** [comment]
Looks good. The templates_test.dart needs to be run with the regenerate goldens option, should I take over that part?

**Comment by mit-mit** [comment]
Yes, please! I know now how that works :-)

**Comment by isoos** [comment]
@jonasfj can you take over the review?
@mit-mit you may need to accept the change I've pushed to this branch.

**Comment by mit-mit** [comment]
Changes look good!

**Comment by jonasfj** [comment]
Justification for override the CLA, bot is that @mit works at Google, I saw him here yesterday :)

**Pull request merged**
