### PR TITLE
Red ribbon for the staging site.

### LINKED ISSUE #7347: Staging should have visual distinction
It is too easy to be confused when on the staging site.

We could add a corner banner similar to the flutter debug one...

### PR DESCRIPTION
**Pull request by isoos**
Fixes #7347.
image

### CODE REVIEW

**Comment by isoos** [comment]
Note: deployed to staging, should be online in ~20 minutes.

**Comment by sigurdm** [comment]
I love it. Only nit is that it makes it hard to click the avatar. Is there a way to make it invisible to mouse-events?

**Review by sigurdm — APPROVED** [review]

**Comment by isoos** [comment]
> Only nit is that it makes it hard to click the avatar.

I think this is more of a feature than a bug. It makes it more apparent that there is something with this site that is not normal.

**Comment by sigurdm** [comment]
perhaps [pointer-events](https://caniuse.com/?search=pointer-events): none

**Comment by sigurdm** [comment]
> I think this is more of a feature than a bug. 

Well it makes the staging site hard to use, not a great feature... I think the visible impression is clear enough

**Review by sigurdm — APPROVED** [review]

**Comment by isoos** [comment]
> perhaps pointer-events: none

Yeah, this helped to fix it. (though it still selects the text, but that's a small issue)

**Pull request merged**
