### PR TITLE
Add new "Add to publisher" admin tool

### PR DESCRIPTION
**Pull request by budde377**
Solves #5936

### CODE REVIEW

**Comment by isoos** [comment]
@budde377: Thanks for this contribution! I have already started to work on a bit more involved changed that uses the invite flow to add new members. We think that it is the desired solution, so if I can do it until the next deployment, we'd go with that. (if not, we shall take this)

**Comment by budde377** [comment]
Sure! Can you advise on a timeline or any other ways to unblock me and regain control of my packages?

**Comment by isoos** [comment]
> Sure! Can you advise on a timeline or any other ways to unblock me and regain control of my packages?

Optimistic scenario: we may deploy a new version in the coming days, which will have this new admin tool one way or the other. Once the new release is stable with 100% traffic migrated, one of the admins will run the invite and then you accept and get control.

However, if something (unrelated to this change) goes wrong, it may be that it will be fixed only early January, since we won't have a new release next week.

**Comment by budde377** [comment]
Appreciate the update this seems like a great timeline, thanks!

**Comment by isoos** [comment]
Closing this in favor of #6293

**Pull request closed without merging**
